# Generated by Django 3.0.6 on 2020-06-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default='1996-12-19T16:39:57-08:00'),
            preserve_default=False,
        ),
    ]
